/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/shoes.glb -d 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shoes.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.074, 0]}>
        <mesh geometry={nodes.Plane013.geometry} material={materials.leather_mat} />
        <mesh geometry={nodes.Plane013_1.geometry} material={materials.collar_padding_mat} />
        <mesh geometry={nodes.Plane013_2.geometry} material={materials.sole_mat} />
        <mesh geometry={nodes.Plane013_3.geometry} material={materials.insole_mat} />
        <mesh geometry={nodes.Plane013_4.geometry} material={materials.stripes_mat} />
        <mesh geometry={nodes.Plane013_5.geometry} material={materials.sew_mat} />
        <mesh geometry={nodes.Plane013_6.geometry} material={materials.laces_mat} />
      </group>
    </group>
  )
}

useGLTF.preload('/shoes.glb')
